### ISSUE TITLE
[Insight] Text files should end with a valid new line character. - in config/packages/twig.yaml, line 4

### ISSUE THREAD

**Issue by TBoileau** [TBoileau/key-privilege#18]
**[in config/packages/twig.yaml, line 4](https://github.com/TBoileau/key-privilege/blob/ed1f985e03431751b22d028f6208eae86d151a48/config/packages/twig.yaml#L4)**

> This file ends with no newline character, or with a different newline character than other files in your project. It won't render properly on a terminal, and it's considered a bad practice.

```
twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_4_layout.html.twig
```

---------------------

_Posted from [SymfonyInsight](https://insight.symfony.com/projects/04cf09ae-3597-41a0-b0f7-bbd22cc011d3/analyses/10)_
